defaults:
  - task: VGG19_on_CIFAR100
  - _self_

__recursive_: True

name: Qwq
run: meta_train
method: group_l2_norm_max_normalizer
log: True
reproduce_index: 0
seed: 7

# no need to change
index: 'train' 

hydra:
  run:
    dir: ./outputs/${task.task_name}/${method}_${task.meta_train.alpha}/${name}/${run}/${index}/${now:%Y-%m-%d_%H-%M-%S}

