defaults:
  - data_generator: VGG19_on_CIFAR100
  - _self_

_recursive_: True 

level: 2
index: 2  # unique index for parrallel generation and merge
num: 3 # number of generated data points
num_proc: 1
method: 'group_sl'


# Follows are defaults, no need to change.

name: ${data_generator.model_name}_on_${data_generator.dataset_name}
model_name: ${data_generator.model_name}
dataset_name: ${data_generator.dataset_name}
save_path: ../dataset_model/${name}_level_${level}_${index}   # path to save the generated dataset
dataset_path: ../dataset/${data_generator.dataset_name}     # path to CIFAR10 for example
cache_path: .cache/${index}

generator:
  _target_: ${data_generator.target}
  _recursive_: True 
  _partial_: True  
  level: ${level}
  method: ${method}
  num: ${num}
  cfg: ${data_generator.cfg}
  cfg_big_dataset: ${big_batch_dataset}
  cfg_small_dataset: ${small_batch_dataset}

dataset:
  dataset_name: ${data_generator.dataset_name}
  num_workers: ${data_generator.num_workers}
  big_batch: ${data_generator.big_batch_size}
  small_batch: ${data_generator.small_batch_size}
  dataset_path: ${dataset_path}
big_batch_dataset:
  dataset_name: ${dataset.dataset_name}
  batch_size: ${dataset.big_batch}
  num_workers: ${dataset.num_workers}
  dataset_path: ${dataset.dataset_path}
small_batch_dataset:
  dataset_name: ${dataset.dataset_name}
  batch_size: ${dataset.small_batch}
  num_workers: ${dataset.num_workers}
  dataset_path: ${dataset.dataset_path}