_recursive_: True

name: Maybe
run: train
index: 0
data_model_num: 2


data_path: "../../imagenet"
model: "resnet50"
pretrained: True

metanetwork:
  _target_: nn.GNN.MyGNN_resnet50
  _recursive_: True
  num_layer: 6
  hiddim: 16
  in_node_dim: 8
  node_res_ratio: 0.0005
  edge_res_ratio: 0.0005

meta_train:
  epochs: 100
  alpha: 16
  bias: False
  opt: "adamw"
  lr_scheduler: "steplr"
  lr : 0.01
  optimize_every_iter: 200
  lr_warmup_epochs: 0
  lr_warmup_method: "linear"
  lr_warmup_decay: 0.1
  lr_decay_milestones : "2"
  lr_gamma : 0.1
  weight_decay : 5e-4
  pruner_reg : 10
  save_every_epoch : 1
  warm_up : 0
  label_smoothing: 0.0
  clip_grad_norm: 0
  print_freq: 200

device: "cuda"
batch_size: 32   # 4gpu 64  8gpu 32
big_batch_size: 32  # 4gpu 64  8gpu 32
epochs: 30
workers: 16
pin_memory: True
opt: "sgd"
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
norm_weight_decay: null
bias_weight_decay: null
transformer_embedding_decay: null
label_smoothing: 0.0
mixup_alpha: 0.0
cutmix_alpha: 0.0
lr_scheduler: "steplr"
lr_decay_milestones: "10"
lr_warmup_epochs: 0
lr_warmup_method: "constant"
lr_warmup_decay: 0.01
lr_gamma: 0.1
lr_min: 0.0
print_freq: 1000
output_dir: "save/${name}/${index}/${run}"
resume: ""
resume_epoch: -1
start_epoch: 0
cache_dataset: True
sync_bn: False
auto_augment: null
ra_magnitude: 9
augmix_severity: 3
random_erase: 0.0


amp: False

no_distribution: False
distributed: False
world_size: -1
rank: -1
gpu: 0
dist_backend: None
dist_url: "env://"
use_deterministic_algorithms: False
interpolation: "bilinear"
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224
clip_grad_norm: null
ra_sampler: False
ra_reps: 3
weights: null

# Pruning parameters
method: "group_l2_norm_max_normalizer"
global_pruning: True
speed_up: 1.3
soft_keeping_ratio: 0.0
reg: 0.0001
delta_reg: 0.0001
max_pruning_ratio: 1.0
data_dependency: False
sparsity_learning: False
sl_epochs: null
sl_resume: null
sl_lr: null
sl_lr_step_size: null
sl_lr_warmup_epochs: null



hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null