model_name: resnet56
dataset_name: CIFAR10
big_batch_size: 500
small_batch_size: 128
num_workers: 4
target: generate_dataset.resnet_generator.resnet56_on_CIFAR10_generator
cfg: 
  speed_up: 2.3
  method: ${method}
  model_name: ${data_generator.model_name}
  dataset_name: ${data_generator.dataset_name}


